/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface FuelSettlementInterface extends ethers.utils.Interface {
  functions: {
    "airline()": FunctionFragment;
    "cancelOrder(uint256)": FunctionFragment;
    "confirmDelivery(uint256)": FunctionFragment;
    "createFuelOrder(address,uint256,uint256)": FunctionFragment;
    "declineOrder(uint256)": FunctionFragment;
    "newOrderId()": FunctionFragment;
    "orders(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "airline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createFuelOrder",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "declineOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "newOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "airline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createFuelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "declineOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newOrderId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;

  events: {
    "DeliveryConfirmed(uint256,uint256)": EventFragment;
    "OrderCreated(uint256,address,uint256)": EventFragment;
    "OrderDeclined(uint256,uint256)": EventFragment;
    "PaymentSettled(uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeliveryConfirmed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OrderCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OrderDeclined"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaymentSettled"): EventFragment;
}

export type DeliveryConfirmedEvent = TypedEvent<
  [BigNumber, BigNumber] & { orderId: BigNumber; timestamp: BigNumber }
>;

export type OrderCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber] & {
    orderId: BigNumber;
    supplier: string;
    totalAmount: BigNumber;
  }
>;

export type OrderDeclinedEvent = TypedEvent<
  [BigNumber, BigNumber] & { orderId: BigNumber; timestamp: BigNumber }
>;

export type PaymentSettledEvent = TypedEvent<
  [BigNumber, string, BigNumber] & {
    orderId: BigNumber;
    recipient: string;
    amount: BigNumber;
  }
>;

export class FuelSettlement extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FuelSettlementInterface;

  functions: {
    airline(overrides?: CallOverrides): Promise<[string]>;

    cancelOrder(
      _orderId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    confirmDelivery(
      _orderId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createFuelOrder(
      _supplier: string,
      _quantityLitres: BigNumberish,
      _pricePerLitre: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    declineOrder(
      _orderId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newOrderId(overrides?: CallOverrides): Promise<[BigNumber]>;

    orders(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber, BigNumber, number, boolean] & {
        orderId: BigNumber;
        supplier: string;
        quantityLitres: BigNumber;
        pricePerLitre: BigNumber;
        totalAmount: BigNumber;
        status: number;
        deliveryConfirmed: boolean;
      }
    >;
  };

  airline(overrides?: CallOverrides): Promise<string>;

  cancelOrder(
    _orderId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  confirmDelivery(
    _orderId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createFuelOrder(
    _supplier: string,
    _quantityLitres: BigNumberish,
    _pricePerLitre: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  declineOrder(
    _orderId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newOrderId(overrides?: CallOverrides): Promise<BigNumber>;

  orders(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, BigNumber, BigNumber, number, boolean] & {
      orderId: BigNumber;
      supplier: string;
      quantityLitres: BigNumber;
      pricePerLitre: BigNumber;
      totalAmount: BigNumber;
      status: number;
      deliveryConfirmed: boolean;
    }
  >;

  callStatic: {
    airline(overrides?: CallOverrides): Promise<string>;

    cancelOrder(
      _orderId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    confirmDelivery(
      _orderId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createFuelOrder(
      _supplier: string,
      _quantityLitres: BigNumberish,
      _pricePerLitre: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    declineOrder(
      _orderId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    newOrderId(overrides?: CallOverrides): Promise<BigNumber>;

    orders(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber, BigNumber, number, boolean] & {
        orderId: BigNumber;
        supplier: string;
        quantityLitres: BigNumber;
        pricePerLitre: BigNumber;
        totalAmount: BigNumber;
        status: number;
        deliveryConfirmed: boolean;
      }
    >;
  };

  filters: {
    "DeliveryConfirmed(uint256,uint256)"(
      orderId?: BigNumberish | null,
      timestamp?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { orderId: BigNumber; timestamp: BigNumber }
    >;

    DeliveryConfirmed(
      orderId?: BigNumberish | null,
      timestamp?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { orderId: BigNumber; timestamp: BigNumber }
    >;

    "OrderCreated(uint256,address,uint256)"(
      orderId?: BigNumberish | null,
      supplier?: string | null,
      totalAmount?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { orderId: BigNumber; supplier: string; totalAmount: BigNumber }
    >;

    OrderCreated(
      orderId?: BigNumberish | null,
      supplier?: string | null,
      totalAmount?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { orderId: BigNumber; supplier: string; totalAmount: BigNumber }
    >;

    "OrderDeclined(uint256,uint256)"(
      orderId?: BigNumberish | null,
      timestamp?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { orderId: BigNumber; timestamp: BigNumber }
    >;

    OrderDeclined(
      orderId?: BigNumberish | null,
      timestamp?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { orderId: BigNumber; timestamp: BigNumber }
    >;

    "PaymentSettled(uint256,address,uint256)"(
      orderId?: BigNumberish | null,
      recipient?: null,
      amount?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { orderId: BigNumber; recipient: string; amount: BigNumber }
    >;

    PaymentSettled(
      orderId?: BigNumberish | null,
      recipient?: null,
      amount?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { orderId: BigNumber; recipient: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    airline(overrides?: CallOverrides): Promise<BigNumber>;

    cancelOrder(
      _orderId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    confirmDelivery(
      _orderId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createFuelOrder(
      _supplier: string,
      _quantityLitres: BigNumberish,
      _pricePerLitre: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    declineOrder(
      _orderId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newOrderId(overrides?: CallOverrides): Promise<BigNumber>;

    orders(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    airline(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelOrder(
      _orderId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    confirmDelivery(
      _orderId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createFuelOrder(
      _supplier: string,
      _quantityLitres: BigNumberish,
      _pricePerLitre: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    declineOrder(
      _orderId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newOrderId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    orders(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
